version: 0.0
os: linux

files:
   - source: /test.jsp
     destination: /root/tomcat/webapps/ROOT
#   - source: /index.html
#     destination: /var/www/html

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: startup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: shutdown.sh
      timeout: 300
      runas: root 
